# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 703feb07ea7f48365b5031ab2a0df6e10e86c8b667c472bae7a11e34ed3d3072959ff974511b62e365ed967e606e8d547fb1777c7de7531440f6849cc2824d41

test:
  secret_key_base: c5a29c332e102deb2632f2efd1a7d74e67ef6adfed27772f7058ada192de2ce152b418c4d5c8aab3dcf8973323d4e2b9a83ba1355e087c98070053bf016e6393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
